### ISSUE TITLE
Example usage with webhooks

### ISSUE THREAD

**Issue by PaulSonOfLars** [NdoleStudio/lemonsqueezy-go#15]
Hi, thank you for the great package! 

I'm wondering if you have any example usages of receiving internal webhooks?
My current expectation is to have to do a `switch` on the event-name Header, but would love to see if thats the best/expected way to work with them!

**Comment by AchoArnold** [comment]
Yep, 

That's how I currently work around them. Another idea is to subscribe to just the `subscription_update` endpoint.

This is an example code which I wrote https://github.com/NdoleStudio/httpsms/blob/main/api/pkg/handlers/lemonsqueezy_handler.go#L79

**Comment by PaulSonOfLars** [comment]
I see, thanks - might be a good idea to link that in the readme somewhere :)

**Comment by AchoArnold** [comment]
I'm not sure I want to go down that route, My idea is everyone should implement it how they please.
