### ISSUE TITLE
Implementing the additional checkout object fields (and more)

### ISSUE THREAD

**Issue by PaulSonOfLars** [NdoleStudio/lemonsqueezy-go#16]
Hi, thanks for the great package - really great to see some existing work being done on lemonsqueezy!

Looking at the  lemonsqueezy docs, I see that the [create checkout](https://docs.lemonsqueezy.com/api/checkouts#create-a-checkout) method has quite a few additional fields which aren't current being exposed by the lib.

Are there any plans to add support for these in the future? I'm specifically looking to change the `product_options.redirect_url` field so that I can link people to my own site.
I would imagine adding these fields now would be a breaking change, so these might need to be added through a refactor, adding golang structs with the omitempty JSON annotation, rather than manually crafted maps that aren't currently in use. (Eg; I faced some errors earlier for not specifying the button colour, even though this isnt something that was necessary for me, and assumedly would have been fine had the field not been specified)

How does that sound? Happy to open a PR for this if there is any interest.

**Comment by AchoArnold** [comment]
Hello @PaulSonOfLars 

While looking at the code again, I see the `redirect_url` field here https://github.com/NdoleStudio/lemonsqueezy-go/blob/main/checkout.go 

Am I missing something?

**Comment by AchoArnold** [comment]
Yep I see now @PaulSonOfLars 

> This is why i suggested reusing the JSON struct passed in as params, with added json and omitempty tags, to make go's marshalling work for us instead; skipping the manual map entirely :)

I like this idea. Feel free to create the PR. I promise to review this promptly.

**Comment by PaulSonOfLars** [comment]
Happy to close this since the PR is in. Thanks @AchoArnold!
