### ISSUE TITLE
Unexpected behavior in License service error return

### ISSUE THREAD

**Issue by raphielscape** [NdoleStudio/lemonsqueezy-go#21]
When I try to Verifying license and it falls to an error with a successful request (e.g Activation Limit reached), rather than returning the response, it instead [returns the raw error code](https://github.com/NdoleStudio/lemonsqueezy-go/blob/cc0f84f4b4546428be06cc51db9bf71bf7384d26/licenses_service.go#L23C3-L23C28) without returning [LicenseActivateApiResponse](https://github.com/NdoleStudio/lemonsqueezy-go/blob/cc0f84f4b4546428be06cc51db9bf71bf7384d26/licenses.go#L6) which contains the proper user-readable error returned by LemonSqueezy as-per the documentation, this seems like not an intended behavior and applicable to all License related services.

**Comment by AchoArnold** [comment]
This is by design @raphielscape 
If the lemonsqueezy API request isn't successful yuo won't get the `LicenseActivateApiResponse` you can get the raw bytes of the repsonse from the `response.Body` [here](https://github.com/NdoleStudio/lemonsqueezy-go/blob/cc0f84f4b4546428be06cc51db9bf71bf7384d26/response.go#L13) you can `json.Umarshall` this into any object you want.

**Comment by raphielscape** [comment]
The API request is successful, but LemonSqueezy returns an error, and it fits LicenseActivateApiResponse, for example in Limit:

```json
{
    "activated": false,
    "error": "This license key has reached the activation limit.",
    "license_key": {
        "id": 412323,
        "status": "active",
        "key": "DB1574D3-5526-4A38-B930-9D7A575BB00D",
        "activation_limit": 1,
        "activation_usage": 1,
        "created_at": "2024-02-15T20:21:30.000000Z",
        "expires_at": "2024-02-29T00:00:00.000000Z",
        "test_mode": true
    },
    "meta": {
        "store_id": 60130,
        "order_id": 2102273,
        "order_item_id": 2063390,
        "variant_id": 212761,
        "variant_name": "Monthly Subscription",
        "product_id": 166918,
        "product_name": "Test",
        "customer_id": 2300686,
        "customer_name": "John Doe",
        "customer_email": "test@example.com"
    }
}
```
I think the error return in the function should be the error returned by LemonSqueezy if LemonSqueezy returned a user-readable error and given that [we are already unmarshalling it](https://github.com/NdoleStudio/lemonsqueezy-go/blob/cc0f84f4b4546428be06cc51db9bf71bf7384d26/licenses_service.go#L27), I don't think repeating the code is a goof thing.

**Comment by AchoArnold** [comment]
We are NOT unmarshalling it. when Lemonsqueezy API doesn't respond with `200`, this line fails https://github.com/NdoleStudio/lemonsqueezy-go/blob/cc0f84f4b4546428be06cc51db9bf71bf7384d26/licenses_service.go#L65

So we don't even do the unmarshalling. Again this is by design.

**Comment by raphielscape** [comment]
Fair enough, although I'm not a fan of repeating code, at least this gave me some optimization space by using sonic instead of JSON for parsing it, Thanks for the reply! :)
