### ISSUE TITLE
Error getting checkout list

### ISSUE THREAD

**Issue by woutercouvaras** [NdoleStudio/lemonsqueezy-go#24]
Hi,

I've only just come across your library, so thanks for putting in the effort to build this!

I'm very, very new to Go (coming from Node land), so i've not put in a PR, because I'm not 100% sure if I'm understanding this correctly.

When I try to get a list of checkouts, here's my code:
```
checkouts, response, err := client.Checkouts.List(context.Background())
if err != nil {
     return err
}

// I have print statements right after, but it's failing before it gets to the print statements
```

I get the following error:

```
json: cannot unmarshal array into Go struct field CheckoutData.data.attributes.checkout_data.custom of type map[string]interface {}
```

When I look at the expected reponse in [lemonsqueezy docs](https://docs.lemonsqueezy.com/api/checkouts#create-a-checkout), it looks like they return an array for `heckoutData.data.attributes.checkout_data.custom`, and when I look at the type, it looks like we're expecting a map:  https://github.com/NdoleStudio/lemonsqueezy-go/blob/81f23ab8f5b7aafed143f043d796ec87cf31f987/checkout.go#L57

Is this correct, or am I misunderstanding something (if I am, I'm sorry to waste your time)?

**Comment by AchoArnold** [comment]
The issue has been fixed @woutercouvaras. Update to the latest version of this library.
