### ISSUE TITLE
Unable to verify lemon squeezy signature on webhook event triggered

### ISSUE THREAD

**Issue by jeffrey0606** [NdoleStudio/lemonsqueezy-go#7]
Hi,
I don't know of this is the right place for this 😅. But I will just try my luck and I need some help.

I am having issues trying to very the lemon squeezy X-Signature string against the secret and request body.
Here is the code:

`
import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
        "io/ioutil"
)

func verifyLemonSqueezySecret(secret string, request *http.Request) bool {

	  signature := request.Header.Get("X-Signature")
  
	  h := hmac.New(sha256.New, []byte(secret))
  
	  body, err := ioutil.ReadAll(request.Body)
  
	  if err != nil {
		  return false
	  }
  
	  h.Write(body)
	  digest := h.Sum(nil)
  
	  fmt.Println("signature: ", signature)
	  fmt.Println("digest: ", hex.EncodeToString(digest))
  
	  if !hmac.Equal([]byte(signature), digest) {
		  return false
	  } else {
		  return true
	  }
   }
`

Thanks,
Jeffrey.

**Comment by AchoArnold** [comment]
Hello, 

Take a look at the webhook verification code here https://github.com/NdoleStudio/lemonsqueezy-go/blob/b6acc31560f8ee29e58dc3f73f045b9cb2c8e1a0/webhooks_service.go#L18C1-L24C1


Your logic should look like this


```go
  signature := request.Header.Get("X-Signature")

  h := hmac.New(sha256.New, []byte(secret))

  body, err := ioutil.ReadAll(request.Body)

  if err != nil {
	  return false
  }

  h.Write(body)
  digest := h.Sum(nil)

  fmt.Println("signature: ", signature)
  fmt.Println("digest: ", hex.EncodeToString(digest))

  return hex.EncodeToString(digest) == signature
```

**Comment by jeffrey0606** [comment]
Hi @AchoArnold , Thank you for your reply.
Here is the output I get when I use the Mock data from `WebhookRequestOrderCreated()`

`secret:  signing-secret`
`signature:  743c0dcfaab3a3d06198183501fb92cc82e548febc80937f3fb236a4932f748f`
`digest:  5cc05c5291b799445915ca1bb5624ad132f1cdd5970c26eefc9192bc98c29410`

And one strange thing I noticed was that modifying(not the json content it self but something like a simple tab alignment) the `WebhookRequestOrderCreated()` Json data yields a different digest.

**Comment by AchoArnold** [comment]
Hey @jeffrey0606,
I'm not sure I understand exactly what your question is or what's making you confused.

Changing any thing in the body of the message will change the hmac digest you can read more about the hmac algorithm here https://en.wikipedia.org/wiki/HMAC?wprov=sfla1

Perhaps you can try getting webhook request from your test lemonsqueezy store even with ngrok and verify that the validation code works correctly

**Comment by Daviduche03** [comment]
> Hey @AchoArnold , It is all good now.
> 
> Thanks again

how did you fix this please

**Comment by AchoArnold** [comment]
I didn't fix anything @Daviduche03 

Read the body of the http request from lemonsqueezy as `[] byte`  ( e.g `body, err := io.ReadAll(r.Body)`) and send it to [this verify method](https://github.com/NdoleStudio/lemonsqueezy-go/blob/b6acc31560f8ee29e58dc3f73f045b9cb2c8e1a0/webhooks_service.go#L18C1-L24C1) with your signing key from lemonsqueezy.
