### ISSUE TITLE
Documentation example doesn't work

### ISSUE THREAD

**Issue by webtaken** [NdoleStudio/lemonsqueezy-go#8]
👋, nice job with the SDK, I like it:
I noticed that in the documentation you instantiate a new client with this code:
```
package main

import (
    "github.com/NdoleStudio/lemonsqueezy-go"
)

func main() {
    client := lemonsqueezy.New(lemonsqueezy.WithAPIKey(""))
}
```
But in my case the lemonsqueezy word isn't recognized, but this worked for me:
```
import (
    "github.com/NdoleStudio/lemonsqueezy-go"
)

var LemonClient *client.Client

func init() {
	LemonClient := client.New(client.WithAPIKey(config.Config("LEMON_SQUEEZY_API_KEY")))
	if LemonClient == nil {
		log.Fatal("Couldn't start LemonSqueezy service")
	}
}
```
Is there something I am missing?

**Comment by AchoArnold** [comment]
Hello @webtaken 
Thanks for your feedback, I solved the issue in this commit https://github.com/NdoleStudio/lemonsqueezy-go/commit/d081c094dc2b6083aa98c0085439f5a0ec30c24b

**Comment by webtaken** [comment]
@AchoArnold Great!
